project:
  type: website
  output-dir: docs
  
website:
  title: "Emma Kinerson's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://in.linkedin.com/in/www.linkedin.com/in/www.linkedin.com/in/emma-kinerson-b73a99213 class="social-icon si-rounded si-small si-linkedin" target="_blank"
      - icon: github
        href: https://github.com/emmakinerson/806WebsiteEK
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Emma Kinerson"

format:
  html:
    theme: Litera
    toc: true

editor: source

